server:
  error:
    include-message: always
    include-binding-errors: always 

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwtdatabase
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true 

  jpa:
    hibernate:
      ddl-auto: create-drop  # ✅ Better for development (use `create-drop` only if needed)
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect  # ✅ Corrected Placement
        format_sql: true
